### ISSUE TITLE
Component cannot be constructed when using a private property called "title"

### ISSUE THREAD

**Issue by albarivas** [salesforce/lwc#1598]
### Description
I have a lwc which has a property called “title”. The component works fine in the org, but when using local development I receive this error: Assert Violation: Failed to construct ‘<c-product-compatibility>’: The result must not have attributes. I changed the name of the property and it works fine now.

#### Steps to Reproduce

https://developer.salesforce.com/docs/component-library/tools/playground/oXsY_GSlm/

#### Expected Results
No error is thrown

#### Actual Results
Error: Assert Violation: Failed to construct '<c-app>': The result must not have attributes.
    at Object.isFalse (https://d3nm9grey5nsoo.cloudfront.net/api/runtime/lwc/0.37.4-220.2/engine.js:189:23)
    at App.set [as title] (https://d3nm9grey5nsoo.cloudfront.net/api/runtime/lwc/0.37.4-220.2/engine.js:7173:28)
    at new App (compiledPreview.js:587:20)
    at invokeComponentConstructor (https://d3nm9grey5nsoo.cloudfront.net/api/runtime/lwc/0.37.4-220.2/engine.js:6517:13)
    at createComponent (https://d3nm9grey5nsoo.cloudfront.net/api/runtime/lwc/0.37.4-220.2/engine.js:6595:9)
    at createVM (https://d3nm9grey5nsoo.cloudfront.net/api/runtime/lwc/0.37.4-220.2/engine.js:7833:9)
    at Object.createElement$2 [as createElement] (https://d3nm9grey5nsoo.cloudfront.net/api/runtime/lwc/0.37.4-220.2/engine.js:8365:9)
    at compiledPreview.js:598:29
    at compiledPreview.js:601:2

### Browsers Affected
Chrome

### Version
Latest

**Possible Solution**
Change the property name or add @track

**Comment by albarivas** [comment]
Not latest version but 220.2

**Comment by Gr8Gatsby** [comment]
FYI: @ntotten @KrisGraySFDC 

@albarivas is this only happening in local development?

**Comment by Gr8Gatsby** [comment]
https://twitter.com/KevinV11n/status/1163683197617467393

**Comment by albarivas** [comment]
> FYI: @ntotten @KrisGraySFDC
> 
> @albarivas is this only happening in local development?

Also in playground

**Comment by ekashida** [comment]
@albarivas Thanks for raising this issue! I just checked and this seems to have been fixed in spring20 but it's not immediately clear which change fixed it. Please reopen if you believe this should be further investigated for a backport into winter20.
