### ISSUE TITLE
No viable path to set up an LWR project on macOS 12.3+

### ISSUE THREAD

**Issue by btfranklin** [salesforce/lwc#2788]
### Description

As far as I can tell, there's no path that a user of macOS 12.3+ can use to create an LWR project in the ways described online. Every version combination I try has some form of failure, and it's not at all clear what alternative approach remains.

#### Steps to Reproduce

I've used nvm as a way to try this with different Node versions, so let's walk through it starting with the only one that used to work (and now doesn't), lts/fermium -> v14.19.1.

```
bt@BTs-MacBook-Pro js % nvm use lts/fermium
Now using node v14.19.1 (npm v8.6.0)
bt@BTs-MacBook-Pro js % npm init lwr
✔ Project directory name: … lwr-project
✔ Select the type of project: › Single Page App
✔ Select a project template: › LWC

Scaffolding project in /Users/bt/Development/js/lwr-project...

Done. Now run:

  cd lwr-project
  npm install
  npm run dev

bt@BTs-MacBook-Pro js % cd lwr-project 
bt@BTs-MacBook-Pro lwr-project % npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated iltorb@2.4.5: The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb
npm ERR! code 1
npm ERR! path /Users/bt/Development/js/lwr-project/node_modules/node-zopfli-es
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.0
npm ERR! gyp info using node@14.19.1 | darwin | x64
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/bt/Development/js/lwr-project/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Development/js/lwr-project/node_modules/node-zopfli-es/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Development/js/lwr-project/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Library/Caches/node-gyp/14.19.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/bt/Library/Caches/node-gyp/14.19.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/bt/Development/js/lwr-project/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/bt/Library/Caches/node-gyp/14.19.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/bt/Development/js/lwr-project/node_modules/node-zopfli-es',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! env: python: No such file or directory
npm ERR! make: *** [Release/nothing.a] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/bt/Development/js/lwr-project/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
npm ERR! gyp ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "/Users/bt/.nvm/versions/node/v14.19.1/bin/node" "/Users/bt/Development/js/lwr-project/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/bt/Development/js/lwr-project/node_modules/node-zopfli-es
npm ERR! gyp ERR! node -v v14.19.1
npm ERR! gyp ERR! node-gyp -v v7.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bt/.npm/_logs/2022-04-12T13_56_40_571Z-debug-0.log
```

Obviously that didn't work. So let's move up to lts/gallium -> v16.14.2.

```
bt@BTs-MacBook-Pro js % nvm use lts/gallium
Now using node v16.14.2 (npm v8.5.0)
bt@BTs-MacBook-Pro js % npm init lwr
✔ Project directory name: … lwr-project
✔ Select the type of project: › Single Page App
✔ Select a project template: › LWC

Scaffolding project in /Users/bt/Development/js/lwr-project...

Done. Now run:

  cd lwr-project
  npm install
  npm run dev

bt@BTs-MacBook-Pro js % cd lwr-project 
bt@BTs-MacBook-Pro lwr-project % npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/asset-transformer@0.6.4',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <15' },
npm WARN EBADENGINE   current: { node: 'v16.14.2', npm: '8.5.0' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated iltorb@2.4.5: The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb
npm ERR! code 1
npm ERR! path /Users/bt/Development/js/lwr-project/node_modules/node-zopfli-es
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.0
npm ERR! gyp info using node@16.14.2 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! (node:76815) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/bt/Development/js/lwr-project/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Development/js/lwr-project/node_modules/node-zopfli-es/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Development/js/lwr-project/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Library/Caches/node-gyp/16.14.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/bt/Library/Caches/node-gyp/16.14.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/bt/Development/js/lwr-project/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/bt/Library/Caches/node-gyp/16.14.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/bt/Development/js/lwr-project/node_modules/node-zopfli-es',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! env: python: No such file or directory
npm ERR! make: *** [Release/nothing.a] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/bt/Development/js/lwr-project/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "/Users/bt/.nvm/versions/node/v16.14.2/bin/node" "/Users/bt/Development/js/lwr-project/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/bt/Development/js/lwr-project/node_modules/node-zopfli-es
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v7.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bt/.npm/_logs/2022-04-12T13_59_53_074Z-debug-0.log
```

No dice. Okay, let's try a more recent version, v17.8.0.

```
bt@BTs-MacBook-Pro js % nvm use 17.8.0    
Now using node v17.8.0 (npm v8.5.5)
bt@BTs-MacBook-Pro js % npm init lwr
✔ Project directory name: … lwr-project
✔ Select the type of project: › Single Page App
✔ Select a project template: › LWC

Scaffolding project in /Users/bt/Development/js/lwr-project...

Done. Now run:

  cd lwr-project
  npm install
  npm run dev

bt@BTs-MacBook-Pro js % cd lwr-project 
bt@BTs-MacBook-Pro lwr-project % npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'lwr-project@0.0.1',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/core@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/types@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/app-service@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/asset-registry@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/asset-transformer@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <15' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/base-template-engine@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/base-view-provider@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/base-view-transformer@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/client-modules@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/compiler@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/diagnostics@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/fs-asset-provider@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/html-view-provider@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/loader@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/lwc-module-provider@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/lwc-ssr@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/markdown-view-provider@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/module-bundler@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/module-registry@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/npm-module-provider@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/nunjucks-view-provider@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/o11y@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/resource-registry@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/router@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/server@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/shared-utils@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/view-registry@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated iltorb@2.4.5: The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb
npm ERR! code 1
npm ERR! path /Users/bt/Development/js/lwr-project/node_modules/node-zopfli-es
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.0
npm ERR! gyp info using node@17.8.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! (node:81394) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/bt/Development/js/lwr-project/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Development/js/lwr-project/node_modules/node-zopfli-es/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Development/js/lwr-project/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Library/Caches/node-gyp/17.8.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/bt/Library/Caches/node-gyp/17.8.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/bt/Development/js/lwr-project/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/bt/Library/Caches/node-gyp/17.8.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/bt/Development/js/lwr-project/node_modules/node-zopfli-es',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! env: python: No such file or directory
npm ERR! make: *** [Release/nothing.a] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/bt/Development/js/lwr-project/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "/Users/bt/.nvm/versions/node/v17.8.0/bin/node" "/Users/bt/Development/js/lwr-project/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/bt/Development/js/lwr-project/node_modules/node-zopfli-es
npm ERR! gyp ERR! node -v v17.8.0
npm ERR! gyp ERR! node-gyp -v v7.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bt/.npm/_logs/2022-04-12T14_02_32_528Z-debug-0.log
```

Welp, that's the worst result of all. So as far as I can tell, it is not possible to use this tooling to create a new LWR project on macOS 12.3+.

**Comment by nolanlawson** [comment]
Thanks for reporting. All of these issues seem related to `node-zopfli-es` as described in https://github.com/salesforce/lwc/issues/2756. It should be fixed in the upcoming version of LWR, as `node-zopfli-es` will be made an optional dependency.

When I run `npm init lwr@0.7.0-alpha.1` on MacOS 11.6.5 Big Sur using node 16.14.2 and npm 8.5.0, I can successfully `npm install` and `npm run dev`. Can you test this and see if it works for you?

**Comment by btfranklin** [comment]
That command does indeed work for me! I tested it using macOS 12.3.1 with node 16.14.2, npm 8.5.0. Awesome, thank you. That's excellent news for the upcoming release.

```
bt@BTs-MacBook-Pro js % npm init lwr@0.7.0-alpha.1
✔ Project directory name: … lwr-project
✔ Select the type of project: › Single Page App
✔ Select a project template: › LWC

Scaffolding project in /Users/bt/Development/js/lwr-project...

Done. Now run:

  cd lwr-project
  npm install
  npm run dev

bt@BTs-MacBook-Pro js % cd lw
cd: no such file or directory: lw
bt@BTs-MacBook-Pro js % cd lwr-project 
bt@BTs-MacBook-Pro lwr-project % npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated iltorb@2.4.5: The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb

added 559 packages, and audited 560 packages in 1m

122 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
bt@BTs-MacBook-Pro lwr-project % npm run dev

> lwr-project@0.0.1 dev
> lwr serve

(node:92793) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
 server running at: port: 3000 | mode: dev
```
