### ISSUE TITLE
Can't get UserRecordAccess with getRecord

### ISSUE THREAD

**Issue by TomSesselmann** [salesforce/lwc#2910]
### Description
When I try to get the UserRecordAccess from any record with the getRecord method I get the following error message in the JavaScript console.

```
Uncaught (in promise) TypeError: Luvio wire adapter Promise<Snapshot> rejected. Original error:
[Cannot read properties of null (reading 'substring')]
    at getObjectMetadata (adsBridge.js:178:31)
    at AdsBridge.emitRecordChanged (adsBridge.js:417:37)
    at eval (adsBridge.js:256:18)
    at Store.broadcast (ldsEngine.js:1600:13)
    at Environment.storeBroadcast (ldsEngine.js:2489:20)
    at Luvio.storeBroadcast (ldsEngine.js:2780:26)
    at obj.<computed> (ldsInstrumentation.js:1291:40)
    at luvio.<computed> [as storeBroadcast] (ldsInstrumentation.js:1463:24)
    at onResourceSuccess$1 (ldsAdaptersUiapi.js:4272:13)
    at eval (ldsAdaptersUiapi.js:4296:50)
```

When I follow the stack trace I can see that's it's trying to get a substring of the id, but the id is null.
<img width="554" alt="Screen Shot 2022-06-29 at 3 20 31 pm" src="https://user-images.githubusercontent.com/23013276/176357798-bf3b4522-03e0-41bd-97c7-71cc1b5a73d3.png">

I wonder if it's because when I try to query the Id of a UserRecordAccess record I get this.
`SELECT UserRecordAccess.Id FROM Account WHERE Id = '0010p000016ZhoMAAS'`
`INVALID_FIELD: Can select only a Has*Access field, and MaxAccessLevel`

#### Steps to Reproduce

```js
import HAS_EDIT_ACCESS from "@salesforce/schema/Account.UserRecordAccess.HasEditAccess";

@wire(getRecord, { recordId: "$recordId", fields: [HAS_EDIT_ACCESS] })
wiredAccountRecord;
```

#### Expected Results
No error is thrown and `wiredAccountRecord.data.fields.UserRecordAccess.value.fields.HasEditAccess.value` exists.

#### Actual Results
Error shown above is thrown.

**Comment by tdalbo92** [comment]
Thanks for the detailed report - we're looking into this now, and will get back to you on how we plan on resolving this.

**Comment by mendioroz87** [comment]
![image](https://github.com/salesforce/lwc/assets/111620949/a18dc115-0720-4763-aad4-f8293b9b5839)

Message
[Luvio wire adapter Promise<Snapshot> rejected. Original error:
[LWC component's @wire target property or method threw an error during value
provisioning. Original error:
[Cannot read properties of undefined (reading 'initialize DependentPicklistManagement')]]]
Component Descriptor
markup://record_flexipage:recordHomeFlexipageUtil
File Name
https://pbcmt.lightning.force.c
am/comnonante/racord flavin
Line
Function
Object.T [as initializePicklistData]
1
Column
5846
Stack Trace
Object.T [as initializePicklistData]
()@https://pbcmt.lightning. force.com/components/record_flexipage/recordHomeF1
exipageUtil.js:1:5846
Object.he [as handleGetPicklistDataViewMode]
()@https://pbcmt.lightning. force.com/components/record_flexipage/recordFieldI
nstancesHandlers. js:1:25425
fp_Lead_Record_Page_Lead.wiredPicklistData_Record()@https://pbcmt.lightning.
force.com/components/forceGenerated/flexipage_Lead_Record_Page_Lead_View_js.
js: 738:69
R.emit()@https://pbcmt.lightning.force.com/components/force/ldsBindings.js:1:
4101
oe.emitOrRefreshRebuiltSnapshot()@https://pbcmt.lightning.force.com/component
s/force/luvioEngine. js: 1:15171
eval()@https://pbcmt. lightning.force.com/components/force/luvioEngine.js:1:10
622
