### ISSUE TITLE
Adding "alternative-text" on lightning-helptext breaks the code

### ISSUE THREAD

**Issue by abhimanyud3dx** [salesforce/lwc#3275]
#### Steps to Reproduce

 <lightning-helptext alternative-text="test" content="You'll receive weekly updates"></lightning-helptext>

```html
 <lightning-helptext alternative-text="test" content="You'll receive weekly updates"></lightning-helptext>
```

#### Expected Results
 Example: No error is throw with a beautiful cute helptext with alt text set as "test"

#### Actual Results
engine.js:253 Uncaught Error: Unknown public property "alternativeText" of element <lightning-helptext>. This is likely a typo on the corresponding attribute "alternative-text".
    at Object.fail (engine.js:253:11)
    at update (engine.js:876:18)
    at Object.create (engine.js:891:22)
    at createCustomElmHook (engine.js:4766:14)
    at Object.create (engine.js:4911:7)
    at createChildrenHook (engine.js:4782:17)
    at Object.insert (engine.js:4892:7)
    at createChildrenHook (engine.js:4783:17)
    at Object.insert (engine.js:4892:7)
    at addVnodes (engine.js:1148:17)

### Browsers Affected

Chrome Version 108.0.5359.125 (Official Build) (64-bit)

**Possible Solution**

USE SLDS

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/13188686/211635840-9cdcc727-59a1-499b-a53c-98db1eed8f4f.png)

**Comment by Templarian** [comment]
This will work in the real component. The playground can't be updated right now due to a technical issue we hope to resolve in the future (essentially rendering old versions of components).

@nolanlawson This can be closed.

**Comment by abhimanyud3dx** [comment]
I tested it on the live [website ](https://www.superqbit.com/app?id=trailhead-leaderboard) build on LWC OSS, I am getting the same error.

![image](https://user-images.githubusercontent.com/13188686/211744534-e7c49e73-78c1-46ef-8367-09fb1c56d4e4.png)

**Comment by Templarian** [comment]
@abhimanyud3dx Can you verify you're using the latest NPM package.

I just pushed `1.17.2-alpha` to `lightning-base-components` (public package). But pushed the internal package also.
