### ISSUE TITLE
LWR Build is not working in both WSL and Windows

### ISSUE THREAD

**Issue by rahulgawale** [salesforce/lwc#3979]
#### Steps to Reproduce
1. Create a new lwr app with single page app option.
2. Add SLDS styling to lwr site.
3. Add lightning base components.
4. Override the layout by providing custom layout html

### lwr.config.json
```json
{
	"lwc": {
		"modules": [
			{"dir": "$rootDir/src/modules"},
			{"npm": "lightning-base-components"},
			{
				"name": "contexts",
				"path": "$rootDir/src/contexts/contexts.js"
			}
		]
	},
	"bundleConfig": {
		"exclude": ["lwc", "lwr/navigation", "@lwc/synthetic-shadow"]
	},
	"routes": [
		{
			"id": "auth-callback",
			"path": "/auth-callback",
			"rootComponent": "page/authCallback",
			"layoutTemplate": "$layoutsDir/auth-callback.html"
		},
		{
			"id": "app",
			"path": "/app",
			"rootComponent": "page/appRoot",
			"layoutTemplate": "$layoutsDir/app.html",
			"bootstrap": {
				"syntheticShadow": true
			}
		},
		{
			"id": "playground",
			"path": "/playground",
			"rootComponent": "page/playground",
			"layoutTemplate": "$layoutsDir/playground.html",
			"bootstrap": {
				"syntheticShadow": true
			}
		},
		{
			"id": "siteRoot",
			"path": "/*",
			"rootComponent": "app/router",
			"layoutTemplate": "$layoutsDir/index.html",
			"bootstrap": {
				"syntheticShadow": true
			}
		}
	],
	"assets": [
		{
			"alias": "assetsDir",
			"dir": "$rootDir/src/assets",
			"urlPath": "/assets"
		},
		{
			"alias": "favicon",
			"file": "$rootDir/src/assets/favicon.ico",
			"urlPath": "/favicon.ico"
		},
		{
			"alias": "jsforceDir",
			"dir": "$rootDir/src/jsforce",
			"urlPath": "/jsforce"
		},
		{
			"dir": "$rootDir/src/assets/fonts",
			"urlPath": "/fonts"
		},
		{
			"file": "$rootDir/src/assets/utilitySprite.svg",
			"urlPath": "/lightning.utilitySprite"
		}
	]
}
```

### Package.json

```json
{
	"name": "lwr-crudspace-spa",
	"version": "0.0.1",
	"license": "MIT",
	"private": true,
	"type": "module",
	"scripts": {
		"clean": "rm -rf node_modules __lwr_cache__ site",
		"dev": "lwr dev",
		"dev:compat": "lwr dev --mode compat",
		"build": "lwr build --clean",
		"build:prod-compat": "lwr build --clean --mode prod-compat",
		"start": "lwr start",
		"stage": "yarn build && yarn start",
		"stage:prod-compat": "yarn build:prod-compat && yarn start"
	},
	"dependencies": {
		"@lwrjs/router": "^0.11.13",
		"jsforce": "^1.11.1",
		"jsforce-ajax-proxy": "^2.0.0",
		"lwc": "5.0.0",
		"lwr": "0.11.13"
	},
	"engines": {
		"node": ">=16.0.0"
	},
	"volta": {
		"node": "18.16.1"
	},
	"devDependencies": {
		"lightning-base-components": "1.21.3-alpha",
		"@salesforce-ux/design-system": "^2.23.2",
		"@lwc/eslint-plugin-lwc": "^1.7.2",
		"@salesforce/eslint-plugin-lightning": "^1.0.0"
	}
}
```

```js
const your => (code) => here;
```

#### Expected Results
lwr build command should generate static site in the `site` folder.

#### Actual Results [Windows]
build command runs into error.
```
 npm run build:prod-compat

> lwr-crudspace-spa@0.0.1 build:prod-compat
> lwr build --clean --mode prod-compat

[info][build] Building lwr application
[info][build] Clearing output directory: site
[error] Unexpected MODIFIER at 1, expected END
TypeError: Unexpected MODIFIER at 1, expected END
    at mustConsume (C:\Projects\lwr-crudspace-spa\node_modules\path-to-regexp\dist\index.js:114:15)
    at parse (C:\Projects\lwr-crudspace-spa\node_modules\path-to-regexp\dist\index.js:172:9)
    at stringToRegexp (C:\Projects\lwr-crudspace-spa\node_modules\path-to-regexp\dist\index.js:329:27)
    at pathToRegexp (C:\Projects\lwr-crudspace-spa\node_modules\path-to-regexp\dist\index.js:407:12)
    at new Layer (C:\Projects\lwr-crudspace-spa\node_modules\@koa\router\lib\layer.js:43:17)
    at Router.register (C:\Projects\lwr-crudspace-spa\node_modules\@koa\router\lib\router.js:570:17)
    at Router.register (C:\Projects\lwr-crudspace-spa\node_modules\@koa\router\lib\router.js:563:23)
    at Router.<computed> [as get] (C:\Projects\lwr-crudspace-spa\node_modules\@koa\router\lib\router.js:200:12)
    at FsInternalServer.get (file:///C:/Projects/lwr-crudspace-spa/node_modules/@lwrjs/server/build/es/fs/fs-server.js:58:24)
    at viewMiddleware (file:///C:/Projects/lwr-crudspace-spa/node_modules/@lwrjs/core/build/es/middleware/view-middleware.js:172:13)
```

#### Actual Results [WSL]
```
rahul@RSG-HP-Laptop:/mnt/c/Projects/lwr-crudspace-spa$ npm run build

> lwr-crudspace-spa@0.0.1 build /mnt/c/Projects/lwr-crudspace-spa
> lwr build --clean

[info][build] Building lwr application
[info][build] Clearing output directory: site
[error] Unexpected MODIFIER at 1, expected END
TypeError: Unexpected MODIFIER at 1, expected END
    at mustConsume (/mnt/c/Projects/lwr-crudspace-spa/node_modules/path-to-regexp/dist/index.js:114:15)
    at parse (/mnt/c/Projects/lwr-crudspace-spa/node_modules/path-to-regexp/dist/index.js:172:9)
    at stringToRegexp (/mnt/c/Projects/lwr-crudspace-spa/node_modules/path-to-regexp/dist/index.js:329:27)
    at pathToRegexp (/mnt/c/Projects/lwr-crudspace-spa/node_modules/path-to-regexp/dist/index.js:407:12)
    at new Layer (/mnt/c/Projects/lwr-crudspace-spa/node_modules/@koa/router/lib/layer.js:43:17)
    at Router.register (/mnt/c/Projects/lwr-crudspace-spa/node_modules/@koa/router/lib/router.js:570:17)
    at Router.register (/mnt/c/Projects/lwr-crudspace-spa/node_modules/@koa/router/lib/router.js:563:23)
    at Router.<computed> [as get] (/mnt/c/Projects/lwr-crudspace-spa/node_modules/@koa/router/lib/router.js:200:12)
    at FsInternalServer.get (file:///mnt/c/Projects/lwr-crudspace-spa/node_modules/@lwrjs/server/build/es/fs/fs-server.js:58:24)
    at viewMiddleware (file:///mnt/c/Projects/lwr-crudspace-spa/node_modules/@lwrjs/core/build/es/middleware/view-middleware.js:172:13)
```

### Version
Node v20.11.0
- LWC: 5.0.0

### Additional info

The `npm run dev ` also renders the site very slow. Everything just works fine until you add lightning-base components.
Please provide a working sample that works on Windows. I tried using rollup but that is also a running issue.

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nolanlawson** [comment]
Thanks for reporting! I've notified the LWR team (LWR is not hosted in this repo, which is for the the LWC open-source framework).

Do you get the same error in WSL? The stacktrace you provide seems to be from raw Windows (cmd.exe or some other terminal I assume).

**Comment by rahulgawale** [comment]
@nolanlawson Yes I am getting a similar error in WSL too. Added the stack trace from WSL to the `Actual Results [WSL]` section. The build works just fine until I add the Lightning Base Components and SLDS. The problem occurs as soon as I add these two.

**Comment by rahulgawale** [comment]
@forcePanda What is supported then? it also doesn't work on Linux. Just curious, Did you raise a case for this?

**Comment by forcePanda** [comment]
Response from support:

> Engineering has logged this as a bug and for now, it looks like it will only work on mac os.
https://issues.salesforce.com/issue/a028c00000yx5yH/lwr-build-is-not-working-in-both-wsl-and-windows

**Comment by rahulgawale** [comment]
@forcePanda Thanks for the update, I hope it will be fixed soon. At least it should work on Linux.

**Comment by nrkruk** [comment]
@rahulgawale it should work on linux / mac osx, can you confirm you are hitting the same error stack trace on linux?

**Comment by nrkruk** [comment]
@forcePanda @rahulgawale if either of you could share your actual github repositories with me (or an example repository that replicates the issue) - I will take a look at it

**Comment by rahulgawale** [comment]
@nrkruk Thanks, I tried to run my code in Mac OSX and it works, but not everyone in our team has that. I have to set up Linux on my machine, once done I will try that out, also I will share the repository tomorrow. Thank you very much for looking into this.

**Comment by forcePanda** [comment]
@nrkruk the build works on Linux but there is an exception. The linux build output fails to show slds icons that are used in lwc base components.

Mac OS works fine for all the scenarios I've come across.

**Comment by rahulgawale** [comment]
@nrkruk Here is the repo with the sample code. - https://github.com/rahulgawale/lwr-site-demo

Please note that I have not added the SLDS assets in the repo, which you can copy from the node module as per the docs - [Set up Salesforce Lightning Design System](https://developer.salesforce.com/docs/platform/lwr/guide/lwr-slds.html?q=styles#set-up-salesforce-lightning-design-system)


As said by @forcePanda build works on Linux with an exception of icons not showing. There are some warnings when `npm run build` command is executed. See the command output below. 

```
rahul@rahul-ubuntu:~/Public/lwr-site-demo$ npm run build

> lwr-site-demo@0.0.1 build
> lwr build --clean

[info][build] Building lwr application
[info][build] Clearing output directory: site
[info][ssg] Static Site Generation
[info][ssg] Building routes (this may take some time to complete)
[info][ssg] en-US / in 732 ms
[warn][ssg] Could not find assets to copy at path: /home/rahul/Public/lwr-site-demo/site/fonts
[warn][ssg] Could not find assets to copy at path: /home/rahul/Public/lwr-site-demo/site/lightning.utilitySprite
[warn][ssg] Could not find assets to copy at path: /home/rahul/Public/lwr-site-demo/site/lightning.standardSprite
[info][ssg] Static Site Generation complete in 2 seconds
rahul@rahul-ubuntu:~/Public/lwr-site-demo$ 
```

# Errors in LWR Docs

I would also like to bring it to your attention that there is a bug in the documentation - i.e. (https://developer.salesforce.com/docs/platform/lwr/guide/lwr-slds.html?q=styles#set-up-salesforce-lightning-design-system)

The `copy-slds.mjs` code does not work at all. It gets executed but does not copy the assets from node module to `/src/assets` folder, so you have to do that manually. 

Also the `package.json` snippet has syntax error, see below.
### Actual snippet: 
There are two (`) back ticks, which are not needed.
```
{
    "scripts": {
        "build": "`node ./scripts/copy-slds.mjs"`
    }
}
```
### Correct snippet:
Removed the back ticks.
```
{
    "scripts": {
        "build": "node ./scripts/copy-slds.mjs"
    }
}
```

Also another issue with the docs is that the commands are not consistent, some pages use `npm` to run commands but some pages use `yarn` so it is kind of confusing. Wondering if package manager has anything to do with the error? Because I am using `npm`.

**Comment by rahulgawale** [comment]
@nrkruk did you get any chance to look into this?

**Comment by juvian** [comment]
> Thanks for reporting! I've notified the LWR team (LWR is not hosted in this repo, which is for the the LWC open-source framework).

@nolanlawson What is the correct way of addressing issues for LWR? Making an issue here? I have been working several months on a website with LWR and sometimes I find bugs that I end up having to solve locally in the files. Sometimes it seems very weird that these things everyone should have issues with persist. Like for example right now I'm stuck with a bug with modals that don't open because isOverlayAllowedToAdd rejects which is caused by the class being imported twice in 2 different bundles

**Comment by nolanlawson** [comment]
@juvian All I can say is that this repo is only concerned with the open-source LWC framework, not with LWR. LWR is currently closed-source, and there is no equivalent GitHub repo we can move this issue to.

If you remain blocked, I would recommend opening a [Salesforce Stack Exchange](https://salesforce.stackexchange.com/questions/tagged/lightning-web-components) question or a [Salesforce case](https://help.salesforce.com/s/).

**Comment by nrkruk** [comment]
@rahulgawale - I did take a look, and there are definitely some path resolution issues we need to fix on windows. I'm working on getting that prioritized with the team but I don't have a definitive timeline on when that will be fixed for you. 

You are correct in that the documentation is wrong here: (https://developer.salesforce.com/docs/platform/lwr/guide/lwr-slds.html?q=styles#set-up-salesforce-lightning-design-system)
If you fix the paths in the script, it will copy the assets as expected:
```
cpx.copy('./node_modules/@salesforce-ux/design-system/assets/**/*', './src/assets', () => {
    console.log('Done copying SLDS resources');
});
```
It also appears that the lightning sprites and the /font directory are not included in the ux design system package, so will need to check on what the correct steps are for those assets. I've filed a bug on our doc team. 

What package manager you use doesn't matter as far as LWR is concerned, both npm and yarn will work fine.

**Comment by juvian** [comment]
I got it to work on windows months ago (at least development mode, prod doesn't work) by changing these files

@lwrjs\asset-registry/build/cjs/index.cjs
```
async delegateGetAsset(assetIdentifier) {
        if (assetIdentifier.specifier.includes('\\') && assetIdentifier.specifier.includes('assets')) {
            assetIdentifier.specifier = assetIdentifier.specifier.replaceAll('\\', '/').replaceAll('//', '/');
        }
```

@lwrjs\module-registry\build\cjs\linker\linker.cjs
```
let link = strategy(importRef, runtimeEnvironment, runtimeParams, signature);
    // replace all locations of importee with the link
    if (link.includes('\\utils') || link.includes('lightning_iconSvgTemplatesUtility')) {
        link = link.replaceAll('\\', '#');
    }
```

@lwrjs\module-registry\build\cjs\index.cjs
```
resolveModuleUriSync
    if (moduleId.specifier.includes('#')) {
        return uri.replaceAll('\\', '_');
    }
```

**Comment by rahulgawale** [comment]
@juvian Thanks for the workaround, I have been using your workaround hoping that someday it will be fixed. Kept using it in dev mode, but now I need to build and deploy my site. At least I expected this to work properly on Linux, but that is not the case either. Honestly, LWC OSS is a great framework but it does not provide any trustworthy build mechanimsm

**Comment by rahulgawale** [comment]
@nolanlawson Could you provide any alternative way to build static LWC OSS site? Maybe using Webpack or Rollup? Something similar to [create-lwc-app](https://github.com/muenzpraeger/create-lwc-app)

**Comment by rahulgawale** [comment]
@nolanlawson I hope you are doing great! Just wanted to check if any update on the fix for the issue. Thanks

**Comment by JimJiraffe** [comment]
Hi, I'm having a similar issue on Windows.

The error results are (after issuing  npm run build ):
[config] peer dependency pwa-kit-runtime was not provided
[info][build] Building lwr application
[info][ssg] Static Site Generation
[info][ssg] Building routes (this may take some time to complete)
[info][ssg] en-US \lwr-info in 15 ms
[error] Failed to get view definition "home"
[error] Could not load /1/bundle/esm/l/en-US/bi/0/module/mi/recipe%2FerrorPanel%23templates%5CnoDataIllustration.css%2Fv%2F1_0_0/latest/bundle_recipe_errorPanel_templates
oDataIllustration_css.js (imported by ../../../../1/bundle/esm/l/en-US/bi/0/module/mi/recipe%2FerrorPanel%23templates%2FnoDataIllustration.html%2Fv%2F1_0_0/latest/bundle_recipe_errorPanel_templates_noDataIllustration_html.js): Cannot read properties of undefined (reading 'linkedModuleRecord')
TypeError: Could not load /1/bundle/esm/l/en-US/bi/0/module/mi/recipe%2FerrorPanel%23templates%5CnoDataIllustration.css%2Fv%2F1_0_0/latest/bundle_recipe_errorPanel_templates
oDataIllustration_css.js (imported by ../../../../1/bundle/esm/l/en-US/bi/0/module/mi/recipe%2FerrorPanel%23templates%2FnoDataIllustration.html%2Fv%2F1_0_0/latest/bundle_recipe_errorPanel_templates_noDataIllustration_html.js): Cannot read properties of undefined (reading 'linkedModuleRecord')
    at Object.load (file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/module-bundler/build/es/utils/rollup-esm-bundler-plugin.js:57:39)
    at file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/rollup/dist/es/shared/rollup.js:22748:40 {
  code: 'PLUGIN_ERROR',
  plugin: 'bundle-plugin',
  hook: 'load',
  watchFiles: [Array]
}
[error] LWR Diagnostic Error: An unexpected error occurred: "Could not load /1/bundle/esm/l/en-US/bi/0/module/mi/recipe%2FerrorPanel%23templates%5CnoDataIllustration.css%2Fv%2F1_0_0/latest/bundle_recipe_errorPanel_templates
oDataIllustration_css.js (imported by ../../../../1/bundle/esm/l/en-US/bi/0/module/mi/recipe%2FerrorPanel%23templates%2FnoDataIllustration.html%2Fv%2F1_0_0/latest/bundle_recipe_errorPanel_templates_noDataIllustration_html.js): Cannot read properties of undefined (reading 'linkedModuleRecord')"

[error] {
  '0': {
    description: {
      category: 'lwrServer/fatal',
      advice: [],
      message: 'An unexpected error occurred: "Could%20not%20load%20/1/bundle/esm/l/en-US/bi/0/module/mi/recipe%252FerrorPanel%2523templates%255CnoDataIllustration.css%252Fv%252F1_0_0/latest/bundle_recipe_errorPanel_templates%0AoDataIllustration_css.js%20%28imported%20by%20../../../../1/bundle/esm/l/en-US/bi/0/module/mi/recipe%252FerrorPanel%2523templates%252FnoDataIllustration.html%252Fv%252F1_0_0/latest/bundle_recipe_errorPanel_templates_noDataIllustration_html.js%29%3A%20Cannot%20read%20properties%20of%20undefined%20%28reading%20%27linkedModuleRecord%27%29"'
    }
  },
  length: 1
}
[error] ServerError: An unexpected error occurred: "Could not load /1/bundle/esm/l/en-US/bi/0/module/mi/recipe%2FerrorPanel%23templates%5CnoDataIllustration.css%2Fv%2F1_0_0/latest/bundle_recipe_errorPanel_templates
oDataIllustration_css.js (imported by ../../../../1/bundle/esm/l/en-US/bi/0/module/mi/recipe%2FerrorPanel%23templates%2FnoDataIllustration.html%2Fv%2F1_0_0/latest/bundle_recipe_errorPanel_templates_noDataIllustration_html.js): Cannot read properties of undefined (reading 'linkedModuleRecord')"

    at createSingleDiagnosticError (file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/diagnostics/build/es/errors.js:6:12)
    at LwrViewRegistry.getViewDefinition (file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/view-registry/build/es/index.js:230:19)
    at async LwrViewHandler.getDefaultRouteViewDefinition (file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/view-registry/build/es/view-handler.js:123:32)
    at async LwrViewHandler.getViewContent (file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/view-registry/build/es/view-handler.js:40:32)
    at async file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/core/build/es/middleware/view-middleware.js:45:28
    at async file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/core/build/es/middleware/utils/error-handling.js:16:13
    at async file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/server/build/es/fs/fs-server.js:61:13
    at async file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/core/build/es/middleware/locale-middleware.js:7:9
    at async file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/server/build/es/fs/fs-server.js:47:13
    at async file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/core/build/es/middleware/request-processor-middleware.js:63:9
    at async file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/server/build/es/fs/fs-server.js:47:13
    at async LwrFsKoa.dispatchUrl (file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/server/build/es/fs/fs-server.js:25:9)
    at async SiteGenerator.dispatchResourceRecursive (file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/core/build/es/tools/static-generation.js:166:23)
    at async SiteGenerator.generateRoute (file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/core/build/es/tools/static-generation.js:129:13)
    at async SiteGenerator.generateRoutesForLocale (file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/core/build/es/tools/static-generation.js:89:13)
    at async SiteGenerator.generateRoutes (file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/core/build/es/tools/static-generation.js:67:13)
    at async SiteGenerator.buildStaticApplication (file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/core/build/es/tools/static-generation.js:44:9)
    at async generateStaticSite (file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/@lwrjs/core/build/es/index.js:196:5)
    at async Command.<anonymous> (file:///C:/Projects/lwc-oss/lwc-recipes-oss/node_modules/lwr/build/es/cli/commands/build.js:68:13)
[info][ssg] en-US \ in 4305 ms
[info][ssg] Static Site Generation complete in 4 seconds

**Comment by PalGenadich** [comment]
@nrkruk, could you please escalate this issue? It became a blocker when I first tried using the LWR, and at this point, I'm not confident in recommending it to others. I will have to explore alternative technologies now.

**Comment by gregwhitworth** [comment]
@PalGenadich @rahulgawale thank you for raising this. I'm the Product Manager of LWR Node and it's been on our backlog to get Windows support for LWR Node but it has been competing with other priorities. I understand that provides **little to no** value to you all in this moment. That said, it would be beneficial to understand what you are you use cases you're using this for as that really helps in strengthening the need for funding it. An [Idea Exchange](https://ideas.salesforce.com/s/) submission would help as well.

And finally, I'm more than happy to jump on a 30 minute call with anyone on this thread to further understand how you're utilizing it and voice additional feedback you may have. DM me on [LinkedIn](https://www.linkedin.com/in/gregwhitworth/) or [Twitter (X)](https://x.com/gregwhitworth) and we can find time.

**Comment by JimJiraffe** [comment]
Thanks Greg,

In my case I have a bunch of custom web services and a custom database
back-end that I need a front-end for, and I was hoping to utilize LWR on
Windows to leverage my LWC/Salesforce skillset.       This company does
have a Salesforce org, but the custom web services and custom database do
not require access to Salesforce in order to operate normally.

I strongly considered just building the front-end on Salesforce, but there
is one single thing keeping me from doing that.   It is 100% critical to
the users that if for any reason Salesforce is unavailable  (including the
case where the end user is not actually a Salesforce user and therefore
cannot use Salesforce anyway),  then this custom UI is STILL available.

Because the existing environment is all Windows-based, with Microsoft
identity management, it seemed like it would be simpler to run LWR on IIS
to simplify the user security and identity management, but I'm unable to
even run it on my own Windows machine in dev mode.

Thanks,
Jim

**Comment by the-last-byte** [comment]
If this doesn't work on windows and it's a known issue - that should be clearer in the docs.  I'm sure I'm not the first to lose a couple of days on this.
