### ISSUE TITLE
lwr project does not run anymore (sudden death)

### ISSUE THREAD

**Issue by AmineId** [salesforce/lwc#4136]
### Description
I'm working on a personal project using LWR, but since an hour ago the project won't run in dev

package.json
{
    "name": "lwr-gymmanager",
    "version": "0.0.1",
    "license": "MIT",
    "private": true,
    "type": "module",
    "scripts": {
        "clean": "rm -rf node_modules __lwr_cache__ site",
        "dev": "lwr dev",
        "dev:compat": "lwr dev --mode compat",
        "build": "lwr build --clean",
        "build:prod-compat": "lwr build --clean --mode prod-compat",
        "start": "lwr start",
        "stage": "yarn build && yarn start",
        "stage:prod-compat": "yarn build:prod-compat && yarn start"
    },
    "dependencies": {
        "@salesforce-ux/design-system": "^2.11.0",
        "bcryptjs": "^2.4.3",
        "bootstrap": "5.3.3",
        "chart.js": "^4.4.2",
        "lightning-base-components": "^1.22.1-alpha",
        "lwc": "^6.2.0",
        "lwr": "^0.12.2",
        "moment": "^2.30.1"
    },
    "engines": {
        "node": ">=18.0.0"
    },
    "volta": {
        "node": "18.18.2"
    }
}

lwr.ocnfig.json
{
    "lwc": {
        "modules": [
            {
                "dir": "$rootDir/src/modules"
            },
            {
                "npm": "lightning-base-components"
            }
        ]
    },
    "bundleConfig": {
        "exclude": [
            "lwc"
        ]
    },
    "routes": [
        {
            "id": "home",
            "path": "/*",
            "rootComponent": "ui/app",
            "layoutTemplate": "$layoutsDir/index.html",
            "bootstrap": {
                "syntheticShadow": true
            }
        }
    ],
    "assets": [
        {
            "alias": "assetsDir",
            "dir": "$rootDir/src/assets",
            "urlPath": "/public/assets"
        },
        {
            "alias": "favicon",
            "file": "$rootDir/src/assets/favicon.ico",
            "urlPath": "/favicon.ico"
        },
        {
            "alias": "sldsDir",
            "dir": "$rootDir/node_modules/@salesforce-ux/design-system/assets",
            "urlPath": "/slds"
        }
    ]
}

#### Steps to Reproduce
npm run dev

```js
export default class App extends LightningElement {

    @track data
    @track screen
    loading = false

    requestBody = {
        "dataSource": DATA_SOURCE,
        "database": DATABASE,
        "collection": ""
    }

    screens = {'home': true, 'findBy': false, 'createMember': false}

    get membersData() {
        return this.data ? this.data.collections.members : false
    }

    get paymentsData() {
        return this.data ? this.data.collections.payments : false
    }

    async makeCallout(url, method, header, body) {
        const response = method === 'GET' ? await fetch(url, {
            method: method,
            headers: header
        }) : await fetch(url, {
            method: method,
            body: JSON.stringify(body),
            headers: header
        })
        return response.json();
    }

    async connectedCallback() {
        try {
            // Get all data
            this.data = await this.makeCallout(uri, 'GET', HEADER, null)

            var dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(this.data))
            var dlAnchorElem = this.refs['downloadAnchorElem']
            dlAnchorElem.setAttribute("href",     dataStr     )
            dlAnchorElem.setAttribute("download", "database.json")
            //dlAnchorElem.click()

            this.loading = false
        } catch(e) {
            console.log(e);
        }
    }

    handleScreen(event) {
        this.screens = {'home': false, 'findBy': false, 'createMember': false}
        const screen = event.detail.screen
        this.screens[screen] = true
        console.log(this.screens);
    }
}
```

#### Expected Results
run to localhost:3000

#### Actual Results
config] peer dependency pwa-kit-runtime was not provided
Application is available at: http://localhost:3000
[error] Failed to get view definition "home"
[error] Unable to find file "H:\Dev Projects\LWR-GymManager\src\__lwr_cache__\lwc_compiled_modules\cache\lwr_esmLoader_0_12_2"
Error: Unable to find file "H:\Dev Projects\LWR-GymManager\src\__lwr_cache__\lwc_compiled_modules\cache\lwr_esmLoader_0_12_2"
    at resolveFileExtension (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/shared-utils/build/es/fs.js:59:15)
    at LwcModuleProvider.createModuleEntry (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/lwc-module-provider/build/es/index.js:237:24)
    at file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/lwc-module-provider/build/es/index.js:160:25
    at InflightTasks.execute (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/shared-utils/build/es/tasks.js:83:23)
    at LwcModuleProvider.getModuleEntry (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/lwc-module-provider/build/es/index.js:159:48)
    at LwrModuleRegistry.delegateGetModuleEntryOnServices (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/index.js:233:43)
    at async resolveRelativeImport (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/module-record.js:20:35)
    at async getModuleRecord (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/module-record.js:75:44)
    at async LwrModuleRegistry.createModuleDefinition (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/index.js:119:30)
    at async file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/index.js:110:31
    at async LwrModuleRegistry.getLinkedModule (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/index.js:148:27)
    at async esmBundler (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-bundler/build/es/esm-bundle-provider.js:25:27)
    at async EsmBundlerProvider.bundle (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-bundler/build/es/esm-bundle-provider.js:16:20)
    at async LwrModuleBundler.<anonymous> (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-bundler/build/es/index.js:64:43)
    at async TaskPool.start (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/shared-utils/build/es/tasks.js:44:25)
[error] LWR Diagnostic Error: An unexpected error occurred: "Unable to find file "H:\Dev Projects\LWR-GymManager\src\__lwr_cache__\lwc_compiled_modules\cache\lwr_esmLoader_0_12_2""

[error] {
  '0': {
    description: {
      category: 'lwrServer/fatal',
      advice: [],
      message: 'An unexpected error occurred: "Unable%20to%20find%20file%20%22H%3A%5CDev%20Projects%5CLWR-GymManager%5Csrc%5C__lwr_cache__%5Clwc_compiled_modules%5Ccache%5Clwr_esmLoader_0_12_2%22"'
    }
  },
  length: 1
}
[error] ServerError: An unexpected error occurred: "Unable to find file "H:\Dev Projects\LWR-GymManager\src\__lwr_cache__\lwc_compiled_modules\cache\lwr_esmLoader_0_12_2""

    at createSingleDiagnosticError (file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/diagnostics/build/es/errors.js:6:12)
    at LwrViewRegistry.getViewDefinition (file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/view-registry/build/es/index.js:230:19)
    at async LwrViewHandler.getDefaultRouteViewDefinition (file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/view-registry/build/es/view-handler.js:123:32)
    at async LwrViewHandler.getViewContent (file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/view-registry/build/es/view-handler.js:40:32)
    at async file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/core/build/es/middleware/view-middleware.js:45:28
    at async file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/core/build/es/middleware/utils/error-handling.js:16:13
    at async file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/server/build/es/express/express-server.js:52:13
[error] Failed to get view definition "home"
[error] Unable to find file "H:\Dev Projects\LWR-GymManager\src\__lwr_cache__\lwc_compiled_modules\cache\lwr_esmLoader_0_12_2"
Error: Unable to find file "H:\Dev Projects\LWR-GymManager\src\__lwr_cache__\lwc_compiled_modules\cache\lwr_esmLoader_0_12_2"
    at resolveFileExtension (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/shared-utils/build/es/fs.js:59:15)
    at LwcModuleProvider.createModuleEntry (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/lwc-module-provider/build/es/index.js:237:24)
    at file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/lwc-module-provider/build/es/index.js:160:25
    at InflightTasks.execute (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/shared-utils/build/es/tasks.js:83:23)
    at LwcModuleProvider.getModuleEntry (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/lwc-module-provider/build/es/index.js:159:48)
    at LwrModuleRegistry.delegateGetModuleEntryOnServices (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/index.js:233:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveRelativeImport (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/module-record.js:20:35)
    at async getModuleRecord (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/module-record.js:75:44)
    at async LwrModuleRegistry.createModuleDefinition (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/index.js:119:30)
    at async file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/index.js:110:31
    at async LwrModuleRegistry.getLinkedModule (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/index.js:148:27)
    at async esmBundler (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-bundler/build/es/esm-bundle-provider.js:25:27)
    at async EsmBundlerProvider.bundle (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-bundler/build/es/esm-bundle-provider.js:16:20)
    at async LwrModuleBundler.<anonymous> (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-bundler/build/es/index.js:64:43)
    at async TaskPool.start (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/shared-utils/build/es/tasks.js:44:25)
[error] LWR Diagnostic Error: An unexpected error occurred: "Unable to find file "H:\Dev Projects\LWR-GymManager\src\__lwr_cache__\lwc_compiled_modules\cache\lwr_esmLoader_0_12_2""

[error] {
  '0': {
    description: {
      category: 'lwrServer/fatal',
      advice: [],
      message: 'An unexpected error occurred: "Unable%20to%20find%20file%20%22H%3A%5CDev%20Projects%5CLWR-GymManager%5Csrc%5C__lwr_cache__%5Clwc_compiled_modules%5Ccache%5Clwr_esmLoader_0_12_2%22"'
    }
  },
  length: 1
}
[error] ServerError: An unexpected error occurred: "Unable to find file "H:\Dev Projects\LWR-GymManager\src\__lwr_cache__\lwc_compiled_modules\cache\lwr_esmLoader_0_12_2""

    at createSingleDiagnosticError (file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/diagnostics/build/es/errors.js:6:12)
    at LwrViewRegistry.getViewDefinition (file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/view-registry/build/es/index.js:230:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LwrViewHandler.getDefaultRouteViewDefinition (file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/view-registry/build/es/view-handler.js:123:32)
    at async LwrViewHandler.getViewContent (file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/view-registry/build/es/view-handler.js:40:32)
    at async file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/core/build/es/middleware/view-middleware.js:45:28
    at async file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/core/build/es/middleware/utils/error-handling.js:16:13
    at async file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/server/build/es/express/express-server.js:52:13
[error] Failed to get view definition "home"
[error] Unable to find file "H:\Dev Projects\LWR-GymManager\src\__lwr_cache__\lwc_compiled_modules\cache\lwr_esmLoader_0_12_2"
Error: Unable to find file "H:\Dev Projects\LWR-GymManager\src\__lwr_cache__\lwc_compiled_modules\cache\lwr_esmLoader_0_12_2"
    at resolveFileExtension (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/shared-utils/build/es/fs.js:59:15)
    at LwcModuleProvider.createModuleEntry (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/lwc-module-provider/build/es/index.js:237:24)
    at file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/lwc-module-provider/build/es/index.js:160:25
    at InflightTasks.execute (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/shared-utils/build/es/tasks.js:83:23)
    at LwcModuleProvider.getModuleEntry (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/lwc-module-provider/build/es/index.js:159:48)
    at LwrModuleRegistry.delegateGetModuleEntryOnServices (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/index.js:233:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveRelativeImport (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/module-record.js:20:35)
    at async getModuleRecord (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/module-record.js:75:44)
    at async LwrModuleRegistry.createModuleDefinition (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/index.js:119:30)
    at async file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/index.js:110:31
    at async LwrModuleRegistry.getLinkedModule (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-registry/build/es/index.js:148:27)
    at async esmBundler (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-bundler/build/es/esm-bundle-provider.js:25:27)
    at async EsmBundlerProvider.bundle (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-bundler/build/es/esm-bundle-provider.js:16:20)
    at async LwrModuleBundler.<anonymous> (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/module-bundler/build/es/index.js:64:43)
    at async TaskPool.start (file:///H:/Dev%20Projects/LWR-GymManager/node_modules/@lwrjs/shared-utils/build/es/tasks.js:44:25)
[error] LWR Diagnostic Error: An unexpected error occurred: "Unable to find file "H:\Dev Projects\LWR-GymManager\src\__lwr_cache__\lwc_compiled_modules\cache\lwr_esmLoader_0_12_2""

[error] {
  '0': {
    description: {
      category: 'lwrServer/fatal',
      advice: [],
      message: 'An unexpected error occurred: "Unable%20to%20find%20file%20%22H%3A%5CDev%20Projects%5CLWR-GymManager%5Csrc%5C__lwr_cache__%5Clwc_compiled_modules%5Ccache%5Clwr_esmLoader_0_12_2%22"'
    }
  },
  length: 1
}
[error] ServerError: An unexpected error occurred: "Unable to find file "H:\Dev Projects\LWR-GymManager\src\__lwr_cache__\lwc_compiled_modules\cache\lwr_esmLoader_0_12_2""

    at createSingleDiagnosticError (file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/diagnostics/build/es/errors.js:6:12)
    at LwrViewRegistry.getViewDefinition (file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/view-registry/build/es/index.js:230:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LwrViewHandler.getDefaultRouteViewDefinition (file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/view-registry/build/es/view-handler.js:123:32)
    at async LwrViewHandler.getViewContent (file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/view-registry/build/es/view-handler.js:40:32)
    at async file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/core/build/es/middleware/view-middleware.js:45:28
    at async file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/core/build/es/middleware/utils/error-handling.js:16:13
    at async file:///H:/Dev Projects/LWR-GymManager/node_modules/@lwrjs/server/build/es/express/express-server.js:52:13

**Additional context/Screenshots**
![image](https://github.com/salesforce/lwc/assets/56881733/a66f52ae-907d-4732-9b8a-3ef3fe09a334)
![image](https://github.com/salesforce/lwc/assets/56881733/1db616ec-1660-4aeb-9893-24e99c24d230)

**Comment by AmineId** [comment]
My bad, i'm importing some kind of lib, mistyped :)
