### ISSUE TITLE
Removal of "vitest/globals" results in conflicting type definition

### ISSUE THREAD

**Issue by ekashida** [salesforce/lwc#4773]
### Description

As of #4740, the `PropertyDescriptor` type used during rollup bundling no longer has a `decorators` property.

Things that were noticed:

`@types/estree` defines a `PropertyDescriptor` without the `decorators` property

<img width="472" alt="Screenshot 2024-11-01 at 18 11 14" src="https://github.com/user-attachments/assets/30d691cb-cc71-4b29-a8d9-0e26c076887a">

`rollup` overrides `estree` with a `PropertyDescriptor` that does have the `decorators` property

<img width="437" alt="Screenshot 2024-11-01 at 18 10 16" src="https://github.com/user-attachments/assets/fa943481-2d9b-48cf-9b83-0e29302ec58d">

It's not clear why rollup is throwing the error when it's the one that has the desired type definition.

#### Steps to Reproduce

Add a reference to `path.node.decorators` somewhere in this [file](https://github.com/salesforce/lwc/blob/2f95ce2def446d3b46ca55682ab38fe430b4e773/packages/%40lwc/ssr-compiler/src/compile-js/index.ts#L53-L67).

```sh
$ yarn
...
$ rollup --config ../../../scripts/rollup/rollup.config.js

      /Users/ekashida/Repos/lwc/packages/@lwc/ssr-compiler/src/index.ts → dist/index.js, dist/index.cjs.js...
      [!] (plugin typescript) RollupError: [plugin typescript] src/compile-js/index.ts (78:59): @rollup/plugin-typescript TS2339: Property 'decorators' does not exist on type 'PropertyDefinition'.
      src/compile-js/index.ts (78:59)

      78         const decorators = (node as EsPropertyDefinition).decorators;
                                                                   ~~~~~~~~~~

          at getRollupError (/Users/ekashida/Repos/lwc/node_modules/rollup/dist/shared/parseAst.js:285:41)
          at Object.error (/Users/ekashida/Repos/lwc/node_modules/rollup/dist/shared/parseAst.js:281:42)
          at Object.error (/Users/ekashida/Repos/lwc/node_modules/rollup/dist/shared/rollup.js:902:32)
          at emitDiagnostic (/Users/ekashida/Repos/lwc/node_modules/@rollup/plugin-typescript/dist/cjs/index.js:571:17)
          at reportDiagnostics (/Users/ekashida/Repos/lwc/node_modules/@rollup/plugin-typescript/dist/cjs/index.js:579:9)
          at Array.forEach (<anonymous>)
          at emitFilesAndReportErrors (/Users/ekashida/Repos/lwc/node_modules/typescript/lib/typescript.js:127124:17)
          at Object.result.afterProgramCreate (/Users/ekashida/Repos/lwc/node_modules/typescript/lib/typescript.js:127283:7)
          at Object.afterProgramCreate (/Users/ekashida/Repos/lwc/node_modules/@rollup/plugin-typescript/dist/cjs/index.js:738:29)
          at synchronizeProgram (/Users/ekashida/Repos/lwc/node_modules/typescript/lib/typescript.js:127652:14)


error Command failed with exit code 1.
```

#### Expected Results

No errors thrown.

#### Actual Results

Error is thrown.

### Version

-   v8.6.0

**Comment by wjhsf** [comment]
For some reason, our IDEs pick up the `rollup` import, but our build script doesn't. One way to solve this is to just make the rollup import explicit (`import type _justNeededForEstreePatch from 'rollup'` in any file, or `import 'rollup'` in a `.d.ts` file). Doing that would require making rollup a runtime dep, though, so it's not a real solution.
